// Feature: github-actions-cicd, Property 5: Inventory generation correctness
// Validates: Requirements 8.6

import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';

/**
 * Replicates the inventory generation logic from environments/dev-github/ansible.tf:
 *
 *   local.ansible_host_entries = join("\n", [
 *     for i, ip in module.compute_asg.instance_ips : "instance_${i + 1} ansible_host=${ip}"
 *   ])
 *
 *   local.ansible_inventory_content = <<-EOT
 *   # Generated by Terraform ...
 *   [dev_instances]
 *   ${local.ansible_host_entries}
 *
 *   [dev_instances:vars]
 *   ansible_user=ec2-user
 *   EOT
 */
function generateInventory(ips: string[]): string {
  const hostEntries =
    ips.length > 0
      ? ips.map((ip, i) => `instance_${i + 1} ansible_host=${ip}`).join('\n')
      : '';

  return [
    '# Generated by Terraform - do not edit by hand. Re-run \'terraform apply\' to update.',
    '[dev_instances]',
    hostEntries,
    '',
    '[dev_instances:vars]',
    'ansible_user=ec2-user',
    '',
  ].join('\n');
}

/** Arbitrary for valid IPv4 addresses. */
const ipv4Arb = fc
  .tuple(fc.integer({ min: 1, max: 255 }), fc.nat({ max: 255 }), fc.nat({ max: 255 }), fc.integer({ min: 1, max: 254 }))
  .map(([a, b, c, d]) => `${a}.${b}.${c}.${d}`);

describe('Property 5: Inventory generation correctness', () => {
  it('for any list of N IPs (N >= 1), the inventory contains exactly N host entries', () => {
    fc.assert(
      fc.property(fc.array(ipv4Arb, { minLength: 1, maxLength: 20 }), (ips) => {
        const inventory = generateInventory(ips);
        const hostLines = inventory
          .split('\n')
          .filter((line) => line.startsWith('instance_'));

        expect(hostLines).toHaveLength(ips.length);
      }),
      { numRuns: 100 }
    );
  });

  it('each host entry follows the format "instance_X ansible_host=<IP>"', () => {
    fc.assert(
      fc.property(fc.array(ipv4Arb, { minLength: 1, maxLength: 20 }), (ips) => {
        const inventory = generateInventory(ips);
        const hostLines = inventory
          .split('\n')
          .filter((line) => line.startsWith('instance_'));

        for (let i = 0; i < ips.length; i++) {
          expect(hostLines[i]).toBe(`instance_${i + 1} ansible_host=${ips[i]}`);
        }
      }),
      { numRuns: 100 }
    );
  });

  it('the inventory always contains the [dev_instances] group header', () => {
    fc.assert(
      fc.property(fc.array(ipv4Arb, { minLength: 1, maxLength: 20 }), (ips) => {
        const inventory = generateInventory(ips);
        expect(inventory).toContain('[dev_instances]');
      }),
      { numRuns: 100 }
    );
  });

  it('the inventory always contains [dev_instances:vars] with ansible_user=ec2-user', () => {
    fc.assert(
      fc.property(fc.array(ipv4Arb, { minLength: 1, maxLength: 20 }), (ips) => {
        const inventory = generateInventory(ips);
        expect(inventory).toContain('[dev_instances:vars]');
        expect(inventory).toContain('ansible_user=ec2-user');
      }),
      { numRuns: 100 }
    );
  });

  it('host indices are sequential starting from 1', () => {
    fc.assert(
      fc.property(fc.array(ipv4Arb, { minLength: 1, maxLength: 20 }), (ips) => {
        const inventory = generateInventory(ips);
        const indices = inventory
          .split('\n')
          .filter((line) => line.startsWith('instance_'))
          .map((line) => parseInt(line.match(/^instance_(\d+)/)?.[1] ?? '0', 10));

        for (let i = 0; i < indices.length; i++) {
          expect(indices[i]).toBe(i + 1);
        }
      }),
      { numRuns: 100 }
    );
  });

  it('[dev_instances:vars] section appears after the host entries', () => {
    fc.assert(
      fc.property(fc.array(ipv4Arb, { minLength: 1, maxLength: 20 }), (ips) => {
        const inventory = generateInventory(ips);
        const hostSectionIdx = inventory.indexOf('[dev_instances]');
        const varsSectionIdx = inventory.indexOf('[dev_instances:vars]');

        expect(varsSectionIdx).toBeGreaterThan(hostSectionIdx);

        // All host entries should appear between the two section headers
        const hostLines = inventory
          .split('\n')
          .filter((line) => line.startsWith('instance_'));
        for (const hostLine of hostLines) {
          const hostIdx = inventory.indexOf(hostLine);
          expect(hostIdx).toBeGreaterThan(hostSectionIdx);
          expect(hostIdx).toBeLessThan(varsSectionIdx);
        }
      }),
      { numRuns: 100 }
    );
  });
});
