# Generate Ansible inventory from Terraform outputs.
# Run 'terraform apply' first; then run Ansible from the repo root:
#   cd ansible && ansible-playbook playbooks/site.yml
locals {
  ansible_host_entries = length(module.compute.instance_public_ips) > 0 ? join("\n", [
    for i, ip in module.compute.instance_public_ips : "instance_${i + 1} ansible_host=${ip}"
  ]) : ""
  ansible_inventory_content = <<-EOT
# Generated by Terraform - do not edit by hand. Re-run 'terraform apply' to update.
[dev_instances]
${local.ansible_host_entries}

[dev_instances:vars]
ansible_user=ec2-user
EOT
}

resource "local_file" "ansible_inventory" {
  content  = local.ansible_inventory_content
  filename = "${path.module}/../../ansible/inventory/terraform_hosts.ini"
}
